name: Node.js CI

on: [push]

jobs:
# Audit job
  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        project: [frontend,api,blockchain,provisioning,e2e-test,excel-export,email-notification]
        
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd TruBudget/${{ matrix.project }}
      - name: Audit project ${{ matrix.project }}
        run: npm audit --audit-level=high
# Test job
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        project: [frontend, api]
        
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd TruBudget/${{ matrix.project }}
      - run: npm ci
      - name: Run tests for ${{ matrix.project }}
        run: npm test
